### ISSUE TITLE
Energy monitor (new HA feature)

### ISSUE THREAD

**Issue by Minims** [cyprieng/gazpar-home-assistant#14]
Can we add those sensor as long term statistics for the Energy panel. Thanks ! 
https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

**Comment by ZeGuigui** [comment]
Not quite sure it would work. LTS sensors require that the entity include "current" values and gazpar only provides yesterday value. But it should not be quite difficult to add the required attributes to the sensor (note that gaz LTS is not yet released inside HA, it will be in an upcoming release)

**Comment by Mincka** [comment]
Just to notify that things are moving quickly about this subject:
https://developers.home-assistant.io/blog/2021/08/16/state_class_total

With `last_reset`, it could have make sense to set it as day n-2 for day n-1 value but since it will be removed, I am not sure that it will be possible to use non-current gazpar statistics. 😞

**Comment by ZeGuigui** [comment]
From what I understand gazpar statistics will be OK as a `total_increasing` sensor which makes sense for water, gaz... Now the problem is to make sure that gazpar api can send a true total_increasing value. If not we will have to stick with measurement and find a way to make sure the daily basis is well understood by HA

**Comment by Mincka** [comment]
Indeed `total_increasing` could work with `sensor.gazpar_energy_month` *but* the value should not decrease during the period otherwise it will be considered as a period reset. You could tell me it should not happen, but GRDF got our back to f*ck it up:

![image](https://user-images.githubusercontent.com/6184289/129929599-01bfd33d-7cc1-4fac-9957-377329cbfe44.png)

Sad workarounds:
1) The custom_components keeps tracks of the values to prevent this
2) A template sensor: https://community.home-assistant.io/t/how-to-filter-sensor-to-get-monotone-increasing-values/254352/5?u=mincka

**Comment by Mincka** [comment]
I tried a poor man's approach to get it working and use a fake volume based on kWh (reversed operation...).

![image](https://user-images.githubusercontent.com/6184289/133109403-21fc4ee1-f9de-4ad8-982d-ed3111ffa292.png)

It almost looks nice. :)

I use two sensor templates and I set the mandatory attributes for the energy dashboard:

```
  - sensor:
      - unique_id: gazpar_energy_total_increasing
        unit_of_measurement: "kWh"
        state: >
          {{ states('sensor.gazpar_energy_month') }}
        attributes:
          friendly_name: Gazpar energy total increasing
          state_class: total_increasing
      - unique_id: gazpar_volume_total_increasing
        unit_of_measurement: "m³"
        state: >
          {{ states('sensor.gazpar_energy_month') | float * 10.7 }}
        attributes:
          friendly_name: Gazpar volume total increasing
          state_class: total_increasing
```

However, because sometimes the returned values for the calculated volume are completely wrong, the stat counter gets reset and I get a huge volume of gaz in the dashboard.

![image](https://user-images.githubusercontent.com/6184289/133110076-b2fd2ca5-1008-4b63-9852-9b7183c85569.png)

Anyway, since the values are the ones reported for the previous day, the gaz is shifted and overall consumption for the home is not real.
