### ISSUE TITLE
Pb installation with Cost

### ISSUE THREAD

**Issue by pbranly** [cyprieng/gazpar-home-assistant#16]
Bonjour,
Je tente de reinstaller votre systeme. ca coince avec cette erreur

Invalid config for [sensor.gazpar]: [cost] is an invalid option for [sensor.gazpar]. Check: sensor.gazpar->cost. (See ?, line ?).

Merci d'avance
Cdlt
Philippe

**Comment by pbranly** [comment]
Apres réécriture du fichier sensor, l’erreur a disparu
Par contre, aucun sensor ne se crée et je ne vois pas d’erreur particulière à ce module dans le log 
Une idée ?
Cdlt
Philippe

**Comment by pbranly** [comment]
Pas de réponse ?

**Comment by pbranly** [comment]
Je viens de le retirer 
Visiblement il n'est plus suivi
Dommage

**Comment by cyprieng** [comment]
Bonjour,

Désolé de ne pas avoir répondu mais je développe ce plugin sur mon temps libre, et comme tout le monde je n'ai pas toujours du temps de disponible.
Quand vous dites "Apres réécriture du fichier sensor, l’erreur a disparu" de quoi parlez vous exactement ?

**Comment by lorisbc** [comment]
Bonjour, j'utilise aussi ce sensor sans aucun soucis. J'ai bien les coûts par jour dans mon dashboard. 
Le code yaml que vous avez correspond-t-il bien à cela (attention aux espaces) ? 

```yaml
sensor:
  - platform: gazpar
    username: !secret gazpar.username
    password: !secret gazpar.password
    cost: 0.045 # Cost per kWh
```

**Comment by pbranly** [comment]
Bonjour 
Merci de répondre. 
Quand j’ai installé le module via HACS et entre configuration de sensor, j’ai d’abord eu l’erreur « Invalid config for [sensor.gazpar]: [cost] is an invalid option for [sensor.gazpar]. Check: sensor.gazpar->cost. (See ?, line ?). »
Puis j’ai refais de zéro la config et cette erreur a disparu.
Mais l’intégration ne me génère rien ( ni sensors si erreurs dans le log)
Voilà le contenu de gazpar.yaml:
sensor:
  - platform: gazpar
    username: !secret gazpar.username
    password: !secret gazpar.password
    cost: 0.0476  # Cost per kWh

cordialement 
Philippe

**Comment by pbranly** [comment]
A chaque ligne il faut un espace ou 2 espaces ? J’ai un espace de mon côté

**Comment by lorisbc** [comment]
> A chaque ligne il faut un espace ou 2 espaces ? J’ai un espace de mon côté

2 espaces.  

Si vous avez mis la configuration dans `gazpar.yaml`, il y a peut être un problème quand vous l'importez dans le `configuration.yaml`.
Le fichier de configuration de home assistant ne doit avoir qu'une seule clé `sensor`.

Par exemple, le code suivant n'est pas valide et seul le dernier sensor sera créé: 
```yaml
sensor:
  - platform: gazpar
sensor:
  - platform: enedis
 ```
 Il faudrait écrire : 
```yaml
sensor:
  - platform: gazpar
  - platform: enedis
```
